### ISSUE TITLE
unbound prefix waveview:deneme

### ISSUE THREAD

**Issue by Mapk26** [dnkilic/android-siri-wave#1]
Hi,

when adding the waveview into the layout with:

<com.dnkilic.waveform.WaveView
            android:id="@+id/vw2"
            **waveview:deneme="true"**
            android:layout_width="wrap_content"
            android:layout_height="wrap_content">

I have an error on waveview:deneme "unbound prefix"

Can you help?

**Comment by dnkilic** [comment]
Hi @Mapk26 i am working on new version of library, next week I will update it. waveview:deneme was experimental

**Comment by dnkilic** [comment]
Resolved by v0.9.5
